version: '3.8'

services:
  db:
    build: ./db
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - ./data:/data
    networks:
      - backend

  app:
    build: .
    container_name: bookshop-flask
    ports: 
      - "5000:5000"
    environment:
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD : "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
    networks:
      - backend

networks:
  backend:
    # Use a custom driver which takes special options
    name: app-network
