version: '3.8'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - backend

  mongo_seed:
    image: mongo
    links:
      - mongodb
    volumes:
      - ./mongo-seed:/mongo-seed
    command:
      sh /mongo-seed/import.sh
    networks:
      - backend

  app:
    build: .
    container_name: bookshop-flask
    ports: 
      - "5000:5000"
    networks:
      - backend

networks:
  backend:
    name: app-network
