version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  sample:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: main

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9.6
    steps:
    - checkout
    - python/install-packages:
        pkg-manager: pip
        # app-dir: ~/project/package-directory/  # If you're requirements.txt isn't in the root directory
    - run:
        name: Run tests
        command: |
          python -m unittest -v

  deploy:
    machine: true
    steps:
    - checkout
    - build:
      name: Build docker image
      command: |
        sh deployment/build.sh
    - deploy-uat:
      name: Deploy to uat
      command: |
        export $(cat deployment/uat.env)
        echo "$CURRENT_ENV"
    - deploy-sit:
      name: Deploy to sit
      command: |
        export $(cat deployment/sit.env)
        echo "$CURRENT_ENV"
    - deploy-prod:
      name: Deploy to prod
      command: |
        export $(cat deployment/prod.env)
        echo "$CURRENT_ENV"
